### ISSUE TITLE
[BUG] Environment variable FIXED_VEC_DIMENSION is not an integer

### ISSUE THREAD

**Issue by marijnl** [a-mma/AquilaDB#54]
**Describe the bug**
When running the docker with --env FIXED_VEC_DIMENSION the Annoy and FAISS fail to initiate because these variables are implictly cast to str, whereas it need to be ints

**To Reproduce**
```
docker run -d -i -p 50051:50051 --env MIN_DOCS2INDEX=1  --env FIXED_VEC_DIMENSION=1000 -v "<local data persist directory>:/data" -t ammaorg/aquiladb:latest
```

Add a doc to aquiladb
```python
from aquiladb import AquilaClient as acl
db = acl('localhost', 50051)

vec_len = 1000

a = [1 for i in range( int(vec_len/2) )]
a.extend([2 for i in range( int(vec_len/2) )])
sample = db.convertDocument(a, {"id": "1"})
print(db.addDocuments([sample]))
```

**Server Logs**
<snippet>
0|vecdb  | running VecID Worker
1|peer_manager  | TypeError: Cannot read property 'rows' of undefined
1|peer_manager  |     at /AquilaDB/src/p2p/routing_table/index.js:157:34
0|vecdb         | running VecID Worker
1|peer_manager  | TypeError: Cannot read property 'rows' of undefined
1|peer_manager  |     at /AquilaDB/src/p2p/routing_table/index.js:157:34
0|vecdb         | running VecID Worker
0|vecdb         | running VecID Worker
1|peer_manager  | TypeError: Cannot read property 'rows' of undefined
1|peer_manager  |     at /AquilaDB/src/p2p/routing_table/index.js:157:34
0|vecdb         | null { total_rows: 2,
0|vecdb         |   offset: 0,
0|vecdb         |   rows:
0|vecdb         |    [ { id: '44a51a50564ff0c68a87f6c55f47e0f6',
0|vecdb         |        key: '44a51a50564ff0c68a87f6c55f47e0f6',
0|vecdb         |        value: [Object],
0|vecdb         |        doc: [Object] },
0|vecdb         |      { id: 'bc59dd1b39ff829a33e3be10c624606e',
0|vecdb         |        key: 'bc59dd1b39ff829a33e3be10c624606e',
0|vecdb         |        value: [Object],
0|vecdb         |        doc: [Object] } ] }
0|vecdb         | 2 ' documents retrieved for faiss index training'
2|vecstore      | Annoy init index
0|vecdb         | { Error: 2 UNKNOWN: Exception calling application: an integer is required (got type str)
0|vecdb         |     at Object.exports.createStatusError (/AquilaDB/src/node_modules/grpc/src/common.js:91:15)
0|vecdb         |     at Object.onReceiveStatus (/AquilaDB/src/node_modules/grpc/src/client_interceptors.js:1209:28)
0|vecdb         |     at InterceptingListener._callNext (/AquilaDB/src/node_modules/grpc/src/client_interceptors.js:568:42)
0|vecdb         |     at InterceptingListener.onReceiveStatus (/AquilaDB/src/node_modules/grpc/src/client_interceptors.js:618:8)
0|vecdb         |     at callback (/AquilaDB/src/node_modules/grpc/src/client_interceptors.js:847:24)
0|vecdb         |   code: 2,
0|vecdb         |   metadata: Metadata { _internal_repr: {}, flags: 0 },
0|vecdb         |   details:
0|vecdb         |    'Exception calling application: an integer is required (got type str)' }
0|vecdb         | running VecID Worker
1|peer_manager  | TypeError: Cannot read property 'rows' of undefined
1|peer_manager  |     at /AquilaDB/src/p2p/routing_table/index.js:157:34

**please complete the following information:**
 - Host OS: Windows 10
 - Docker image label (tag) latest

**Comment by marijnl** [comment]
#57
